const config = {
    api: {
        base: 'https://api-rvm.endlos.live/api/v1/',
        url: {
            login: 'user/login',
            refresh: 'auth/refreshtoken',
            inventory:'inventry/get?type=all',
            getallCustomers:'customer/getAll',
            addCustomer:'customer/add',
            updateCustomer:'customer/update',
            getCustomerById:'customer/get',
            getBranchesById:'branch/getbycustomer',
            addBranch:'branch/add',
            updateBranch:'branch/update',
            deleteBranch:'branch/delete',
            deleteCustomer:'customer/delete',
            inventoryType:'inventrytype/getAll?type=allInventries',
            addInventoryType:'inventrytype/add',
            updateInventoryType:'inventrytype/update',
            deleteInventoryType:'inventrytype/delete',
            getInventoryTypeById:'inventrytype/get',
            addInventory:'inventry/add',
            getInventory:'inventry/get?type=all',
            updateInventory:'inventry/update',
            deleteInventory:'inventry/delete',
            getAllMachines:'machine/get?type=all',
            deleteMachine:'machine/delete',
            addMachine:'machine/add',
            updateMachine:'machine/update',
            assignMachine:'machine/assign',
            updateassignMachine:'machine/assign',
            addRole:"userrole",
            getRole:"userrole",
            deleteRole:"userrole",
            addRole:"userrole",
            updateRole:"userrole",
            getUser:"/user/getAll",
            register:"/user/register",
            updateUser:"/user",
            deleteUser:"/user",
            getProblems:"problem/getAll",
            addProblem:"problem",
            deletProblem:"problem",
            updateProblem:"problem"
        }
    }
}
export default config;